pub struct StaticIpo {
    pub ticker: &'static str,
    pub name: &'static str,
    pub date: &'static str,
    pub price: f64,
    pub status: &'static str,
    pub book_building: &'static str,
    pub trading_start: &'static str,
    pub dist_type: &'static str,
    pub participant_count: &'static str,
}

pub const RECENT_IPOS: &[StaticIpo] = &[
    StaticIpo { ticker: "SARAE", name: "Şa-Ra Enerji", date: "2026-07-10", price: 70.00, status: "TALEP TOPLAMA", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
    StaticIpo { ticker: "SSAAT", name: "Saat ve Saat", date: "2026-07-08", price: 56.00, status: "TALEP TOPLAMA", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
    StaticIpo { ticker: "ISVEA", name: "İsvea Seramik", date: "2026-07-03", price: 20.90, status: "AKTİF", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
    StaticIpo { ticker: "EKIM", name: "Intercity Ekim Turizm", date: "2026-07-03", price: 30.26, status: "AKTİF", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
    StaticIpo { ticker: "GOLDA", name: "Golda Gıda", date: "2026-07-02", price: 9.20, status: "AKTİF", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
    StaticIpo { ticker: "SOHOE", name: "Soho Giyim ve Enerji", date: "2026-07-01", price: 15.00, status: "AKTİF", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
    StaticIpo { ticker: "ORZAX", name: "Orzaks İlaç", date: "2026-07-01", price: 69.00, status: "AKTİF", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
    StaticIpo { ticker: "BETAE", name: "Beta Enerji", date: "2026-06-25", price: 40.00, status: "AKTİF", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
    StaticIpo { ticker: "EKDMR", name: "Ekinciler Demir ve Çelik", date: "2026-05-13", price: 45.00, status: "TAMAMLANDI", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
    StaticIpo { ticker: "ENPRA", name: "Enpara Bank A.Ş.", date: "2026-04-07", price: 190.00, status: "TAMAMLANDI", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
    StaticIpo { ticker: "AAGYO", name: "Ağaoğlu Avrasya GYO", date: "2026-04-01", price: 21.10, status: "TAMAMLANDI", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
    StaticIpo { ticker: "MCARD", name: "MetropolCard", date: "2026-03-02", price: 80.00, status: "TAMAMLANDI", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
    StaticIpo { ticker: "LXGYO", name: "Luxera GYO", date: "2026-03-02", price: 12.05, status: "TAMAMLANDI", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
    StaticIpo { ticker: "GENKM", name: "Gentaş Kimya", date: "2026-03-02", price: 11.00, status: "TAMAMLANDI", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
    StaticIpo { ticker: "SVGYO", name: "Savur GYO", date: "2026-02-26", price: 3.64, status: "TAMAMLANDI", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
    StaticIpo { ticker: "HOROZ", name: "Horoz Lojistik", date: "2024-06-07", price: 55.00, status: "TAMAMLANDI", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
    StaticIpo { ticker: "ALTNY", name: "Altınay Savunma", date: "2024-05-16", price: 32.00, status: "TAMAMLANDI", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
    StaticIpo { ticker: "KOCMT", name: "Koç Metalurji", date: "2024-05-17", price: 20.50, status: "TAMAMLANDI", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
    StaticIpo { ticker: "HARES", name: "Hareket Proje", date: "2024-05-24", price: 70.00, status: "TAMAMLANDI", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
    StaticIpo { ticker: "ENTRA", name: "Entra Yenilenebilir Enerji", date: "2024-04-04", price: 10.00, status: "TAMAMLANDI", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
    StaticIpo { ticker: "RGYAS", name: "Rönesans Gayrimenkul", date: "2024-04-26", price: 135.00, status: "TAMAMLANDI", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
    StaticIpo { ticker: "ODINE", name: "Odine Teknoloji", date: "2024-03-21", price: 30.00, status: "TAMAMLANDI", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
    StaticIpo { ticker: "ALVES", name: "Alves Kablo", date: "2024-02-29", price: 19.45, status: "TAMAMLANDI", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
    StaticIpo { ticker: "ARTMS", name: "Artemis Halı", date: "2024-03-04", price: 25.35, status: "TAMAMLANDI", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
    StaticIpo { ticker: "OBAMS", name: "Oba Makarnacılık", date: "2024-03-01", price: 39.24, status: "TAMAMLANDI", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
    StaticIpo { ticker: "MOGAN", name: "Mogan Enerji", date: "2024-03-01", price: 11.33, status: "TAMAMLANDI", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
    StaticIpo { ticker: "BOBET", name: "Boğaziçi Beton", date: "2024-02-22", price: 21.00, status: "TAMAMLANDI", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
    StaticIpo { ticker: "LMKDC", name: "Limak Doğu Anadolu Çimento", date: "2024-02-22", price: 16.20, status: "TAMAMLANDI", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
    StaticIpo { ticker: "BORLS", name: "Borlease Otomotiv", date: "2023-10-18", price: 25.29, status: "TAMAMLANDI", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
    StaticIpo { ticker: "TABGD", name: "TAB Gıda", date: "2023-10-26", price: 130.00, status: "TAMAMLANDI", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
    StaticIpo { ticker: "REEDR", name: "Reeder Teknoloji", date: "2023-09-21", price: 9.30, status: "TAMAMLANDI", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
    StaticIpo { ticker: "TARKM", name: "Tarkim Bitki Koruma", date: "2023-09-12", price: 107.50, status: "TAMAMLANDI", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
    StaticIpo { ticker: "EBEBK", name: "Ebebek Mağazacılık", date: "2023-09-07", price: 46.50, status: "TAMAMLANDI", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
    StaticIpo { ticker: "KZGYO", name: "Kuzey Boru", date: "2023-12-14", price: 36.20, status: "TAMAMLANDI", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
    StaticIpo { ticker: "MEKAG", name: "Meka Beton", date: "2023-10-12", price: 25.00, status: "TAMAMLANDI", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
    StaticIpo { ticker: "SURGY", name: "Sur Tatil Evleri", date: "2023-12-14", price: 49.18, status: "TAMAMLANDI", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
    StaticIpo { ticker: "CATES", name: "Çates Elektrik", date: "2023-12-07", price: 57.15, status: "TAMAMLANDI", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
    StaticIpo { ticker: "BEGYO", name: "Batı Ege GYO", date: "2023-12-08", price: 3.00, status: "TAMAMLANDI", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
    StaticIpo { ticker: "SKYMD", name: "Şeker Yatırım", date: "2023-12-06", price: 7.00, status: "TAMAMLANDI", book_building: "", trading_start: "", dist_type: "", participant_count: "" },
];
